import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { cn } from "@/lib/utils";

import Providers from "@/providers";

import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script
                    defer
                    src="https://umami-self-gamma.vercel.app/script.js"
                    data-website-id="07122b5b-464e-4052-ab40-8ab3847b458f"
                />
            </head>
            <body
                className={cn(
                    `relative scroll-smooth bg-background p-6 antialiased lg:h-screen lg:overflow-x-hidden`,
                    geistSans.className,
                )}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
